[0m19:01:30.861527 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107d0b380>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109a879d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109a87890>]}


============================== 19:01:30.865041 | bafa06a5-072d-4402-8d53-a8d38510b9fb ==============================
[0m19:01:30.865041 [info ] [MainThread]: Running with dbt=1.10.4
[0m19:01:30.865485 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '/Users/shawn/.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt init', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m19:01:30.874563 [info ] [MainThread]: Creating dbt configuration folder at /Users/shawn/.dbt
[0m19:01:37.792101 [debug] [MainThread]: Starter project path: /Applications/miniconda3/lib/python3.13/site-packages/dbt/include/starter_project
[0m19:01:37.803085 [info ] [MainThread]: 
Your new dbt project "ny_taxi" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m19:01:37.803661 [info ] [MainThread]: Setting up your profile.
[0m19:01:37.804626 [error] [MainThread]: Encountered an error:
Runtime Error
  No adapters available. Learn how to install an adapter by going to https://docs.getdbt.com/docs/connect-adapters#install-using-the-cli
[0m19:01:37.827023 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 7.009026, "process_in_blocks": "0", "process_kernel_time": 0.170652, "process_mem_max_rss": "116555776", "process_out_blocks": "0", "process_user_time": 0.76483}
[0m19:01:37.827653 [debug] [MainThread]: Command `dbt init` failed at 19:01:37.827525 after 7.01 seconds
[0m19:01:37.828088 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109a9be10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109b4e450>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1099528b0>]}
[0m19:01:37.828418 [debug] [MainThread]: Flushing usage events
[0m19:01:38.801033 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m01:29:18.983884 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11370f380>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1159939d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x115993890>]}


============================== 01:29:18.987650 | 6f700dd9-7662-4e64-b5c1-8b9202b0cb22 ==============================
[0m01:29:18.987650 [info ] [MainThread]: Running with dbt=1.10.4
[0m01:29:18.987999 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/Users/shawn/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt init', 'send_anonymous_usage_stats': 'True'}
[0m01:29:22.103084 [debug] [MainThread]: Starter project path: /Applications/miniconda3/lib/python3.13/site-packages/dbt/include/starter_project
[0m01:29:22.107455 [info ] [MainThread]: 
Your new dbt project "ny_taxi" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m01:29:22.107682 [info ] [MainThread]: Setting up your profile.
[0m01:30:15.330625 [info ] [MainThread]: Profile ny_taxi written to /Users/shawn/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m01:30:15.359914 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 56.42384, "process_in_blocks": "0", "process_kernel_time": 0.221454, "process_mem_max_rss": "114900992", "process_out_blocks": "0", "process_user_time": 0.860863}
[0m01:30:15.360900 [debug] [MainThread]: Command `dbt init` succeeded at 01:30:15.360741 after 56.43 seconds
[0m01:30:15.361878 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x115ab2190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x114153e30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x115a6cf30>]}
[0m01:30:15.362508 [debug] [MainThread]: Flushing usage events
[0m01:30:16.582853 [debug] [MainThread]: An error was encountered while trying to flush usage events
